version: "3.3"
services:
  postgres:
    image: "postgres:15"
    env_file: .env
    environment:
      - "POSTGRES_PASSWORD=$DATABASE_PASSWORD"
      - "POSTGRES_USER=$DATABASE_USER"
      - "POSTGRES_DB=$DATABASE_NAME"
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - "./psql-local:/local"

volumes:
  database: