# Generated by Django 4.1.5 on 2023-01-04 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fiber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('main_needle', models.FloatField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finishing_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recipient', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('planned', 'planned'), ('in progress', 'in progress'), ('finished', 'finished'), ('frogged', 'frogged')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='YarnType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200)),
                ('base', models.CharField(max_length=200)),
                ('meterage', models.IntegerField()),
                ('fiber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yarnjournal.fiber')),
            ],
            options={
                'unique_together': {('brand', 'base')},
            },
        ),
        migrations.CreateModel(
            name='StashEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('weight', models.IntegerField()),
                ('colour_code', models.CharField(blank=True, max_length=200, null=True)),
                ('dye_lot', models.CharField(blank=True, max_length=200, null=True)),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yarnjournal.colour')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='yarnjournal.project')),
                ('yarn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yarnjournal.yarntype')),
            ],
        ),
    ]
