# Generated by Django 4.1.5 on 2023-01-03 16:08

from django.db import migrations


def set_intial_colours(apps, schema_editor):
    Colour = apps.get_model('yarnjournal', 'Colour')
    initial_colours = ('Blue', 'Red', 'Yellow', 'Orange', 'Pink', 'Purple', 'Green', 'Turquoise', 'Gray', 'White', 'Black', 'Brown', 'Beige')
    for colour in initial_colours:
        Colour(name=colour).save()

def set_intial_fibers(apps, schema_editor):
    Fiber = apps.get_model('yarnjournal', 'Fiber')
    initial_fibers = ('Norwegian wool', 'Blend', 'Norwegian peltwool', 'Wool', 'Cotton', 'Linen', 'Silk mohair', 'Silk', 'Polyester')
    for fiber in initial_fibers:
        Fiber(name=fiber).save()

class Migration(migrations.Migration):

    dependencies = [
        ('yarnjournal', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(set_intial_colours),
        migrations.RunPython(set_intial_fibers),
    ]
