# Generated by Django 4.1.5 on 2023-01-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarnjournal', '0002_auto_20230103_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
