# Generated by Django 4.1.5 on 2023-01-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yarnjournal', '0003_project_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in progress', 'In progress'), ('finished', 'Finished'), ('frogged', 'Frogged')], max_length=200),
        ),
    ]
